[package]
name = "aim-simulator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aim-decoders = { version = "0.3.4", path = "../core/decoders" }
aim-protocols = { version = "0.3.4", path = "../core/protocols" }
aim-transport = { version = "0.3.4", path = "../core/transport", default-features = false }
aim-types = { version = "0.3.4", path = "../core/types" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[dev-dependencies]
aim-adapter = { version = "0.3.4", path = "../core/adapter", default-features = false }
