[package]
name = "aim-decoders"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aim-protocols = { version = "0.3.9", path = "../protocols" }
aim-types = { version = "0.3.9", path = "../types" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml_ng = "0.10.0"
tracing = "0.1.44"
