[package]
name = "aim-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aim-diagnostics = { version = "0.3.7", path = "../diagnostics", default-features = false }
aim-safety = { version = "0.3.7", path = "../safety" }
aim-types = { version = "0.3.7", path = "../types" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[dev-dependencies]
aim-decoders = { version = "0.3.7", path = "../decoders" }
aim-session = { version = "0.3.7", path = "../session" }
aim-simulator = { version = "0.3.7", path = "../../simulator" }
aim-adapter = { version = "0.3.7", path = "../adapter", default-features = false }

[features]
default = ["serial"]
serial = ["aim-diagnostics/serial"]
